-- -----------------------------------------------------
-- Table `SVC_CMT_GROUP`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SVC_CMT_GROUP` (
  `UID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `NAME` VARCHAR(50) NOT NULL COMMENT '댓글 그룹 이름',
  `DESCRIPTION` VARCHAR(1000) NULL DEFAULT NULL COMMENT '설명',
  `LINK_KEY` VARCHAR(100) NOT NULL COMMENT 'UID 외에 댓글 그룹을 연결 할 키(Key)\\nex) 게시글의 URL',
  `PAGE_SIZE` TINYINT(3) UNSIGNED NOT NULL DEFAULT 20 COMMENT '기본 페이지당 게시물 갯수',
  `SORT_COLUMNS` VARCHAR(100) NOT NULL DEFAULT 'createdDate DESC' COMMENT '정렬 컬럼 및 방식, 세미콜론으로 구분(;)',
  `LEVEL_LIMIT` TINYINT(3) UNSIGNED NOT NULL DEFAULT 1 COMMENT 'Reply Level 제한(0: 무제한)',
  `USE_LIKE` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '좋아요 기능 사용 여부',
  `USE_RECOMMEND` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '추천/반대 기능 사용 여부',
  `USE_POINT` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '점수(별점) 기능 사용 여부',
  `USE_HTML` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '내용에 HTML 사용 여부',
  `USE_MARKDOWN` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '내용에 Markdown 사용 여부',
  `USE_DEL_RESTRICT` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '삭제 제한 사용 여부(reply가 있을 경우 삭제 불가)',
  `CHAR_LIMIT_TYPE` CHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제 제한 사용 여부(reply가 있을 경우 삭제 불가)',
  `CHAR_LIMIT_CNT` INT(5) UNSIGNED NOT NULL DEFAULT 0 COMMENT '제한 량',
  `IS_DEL` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '삭제 여부',
  `REG_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록 일시',
  `REG_USER_ID` VARCHAR(20) NOT NULL COMMENT '등록 사용자 ID',
  `MOD_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '최종 수정 일시',
  `MOD_USER_ID` VARCHAR(20) NOT NULL COMMENT '최종 수정 사용자 ID',
  PRIMARY KEY (`UID`)
)
COMMENT = '댓글 그룹';

CREATE INDEX `IDX_CMT_GROUP_1` ON `SVC_CMT_GROUP` (`IS_DEL` ASC, `UID` ASC);
CREATE INDEX `IDX_CMT_GROUP_2` ON `SVC_CMT_GROUP` (`IS_DEL` ASC, `LINK_KEY` ASC);


-- -----------------------------------------------------
-- Table `SVC_CMT_BASIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SVC_CMT_BASIC` (
  `UID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Unique ID',
  `GROUP_UID` BIGINT(20) UNSIGNED NOT NULL COMMENT '그룹 Unique ID',
  `PARENT_UID` BIGINT(20) UNSIGNED NULL COMMENT '부모 댓글 Unique ID',
  `REPLY_LEVEL` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Reply Level',
  `SUMMARY_CONTENT` VARCHAR(1000) NOT NULL COMMENT '내용 요약(미리보기)',
  `CONTENT` LONGTEXT NULL COMMENT '내용',
  `LIKE_CNT` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '좋아요 개수',
  `RECOMMEND_CNT` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '추천 개수',
  `OPPOSE_CNT` BIGINT(20) UNSIGNED NOT NULL DEFAULT 0 COMMENT '반대 개수',
  `AVG_POINT` DECIMAL(10, 2) NOT NULL DEFAULT 0 COMMENT '평균 점수',
  `IS_BLIND` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '블라인드 여부',
  `IS_DEL` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '삭제 여부',
  `REG_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() COMMENT '등록 일시',
  `REG_USER_ID` VARCHAR(20) NOT NULL COMMENT '등록 사용자 ID',
  `MOD_DATETIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP() COMMENT '최종 수정 일시',
  `MOD_USER_ID` VARCHAR(20) NOT NULL COMMENT '최종 수정 사용자 ID',
  PRIMARY KEY (`UID`)
)
COMMENT = '댓글';

CREATE INDEX `IDX_CMT_BASIC_1` ON `SVC_CMT_BASIC` (`IS_DEL` ASC, `GROUP_UID` ASC, `PARENT_UID` ASC, `UID` ASC);